server:
  port: 8080
  servlet:
    contextPath: /gastalon

spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/gastalon
    username: root
    password: root
  #JPA Properties
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.temp.use_jdbc_metadata_defaults: false  #Added to avoid de CLOB Exception
